### PR TITLE
[DO NOT MERGE] testing travis custom messages

### PR DESCRIPTION
**Pull request by forejtv**

### CODE REVIEW

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by forejtv** [comment]
retest this please

**Comment by rjmunro** [comment]
If this is not to be merged, can it now be closed?

**Pull request closed without merging**
